### ISSUE TITLE
Need to log in more frequently on MSK Portal

### ISSUE THREAD

**Issue by inodb** [knowledgesystems/knowledgesystems-k8s-deployment#220]
People have reported that they need to sign in more often

From Walid:

>Hey, I just pinged Henry since he had first brought it up and I started noticing it after. I think its at least 4 months, but maybe closer to 6 months (~February).
It pretty much requires you to log in every morning (after a certain time at night) and also maybe ever ~1 hour or so.

**Comment by inodb** [comment]
Thanks so much for fixing this @hweej - could you describe how you changed this? Thanks!

**Comment by hweej** [comment]
Sure! I have changed the SSO Session Idle time in KeyCloak from 30 minutes to 8 hours. This is the time a session can remain idle before expiring. After, this time the user will have to request another valid session. This is likely the cause triggering a re-login more often than we'd like. 

This change is at the realm level and will be reflected across all of our portals MSK Portal, triage, and private.
