### ISSUE TITLE
Create a Persistent Mongo Cache that can be Mounted by a GN Pod on Startup

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/knowledgesystems-k8s-deployment#43]
Currently there is no backup of the Mongo DB used to cache Genome Nexus variant annotations.  Setup daily Mongo DB dump to S3 for use during recovery of Mongo pod crash.

Done condition : on restart of the mongo server in kubernetes ... the persisted cache of mongo contents is loaded from backup.  Backups are made on a daily bases of the mongo contents (avoiding corruption / loss of integrity)

Consider leveraging the VEP cache mounting tool.

**Comment by ao508** [comment]
- [x] k8s cronjob configured 
- [ ] helm downloads latest version of cache from s3 bucket
