### ISSUE TITLE
Where to access portal-configuration?

### ISSUE THREAD

**Issue by weberc2-tempus** [knowledgesystems/knowledgesystems-k8s-deployment#95]
I'm trying to follow along with the Kubernetes installation procedures, but it seems like many resources depend on a configmap in some portal-configuration directory? I'm guessing this is meant to be customized for each individual installation, but I can't find any information about the schema for this config map. Apologies if this is documented somewhere an I simply haven't seen it.

**Comment by inodb** [comment]
@weberc2-tempus good point - we haven't really described what that configmap looks like. We store some of those in a private repo because of their privacy sensitive nature. If there is a specific configmap you're interested in I can share it with credentials hidden
